module.exports = {
  locales: ['en', 'ro'],
  defaultLocale: 'en',
  pages: {
    '*': ['common', 'nav', 'footer'],
    '/': ['home', 'hero', 'usp', 'cabin', 'testimonials', 'gallery'],
    '/cabana': ['cabin'],
    '/about': ['cabin'],
    '/contact': ['contact'],
    '/faq': ['faq'],
    '/galerie': ['gallery'],
    '/gallery': ['gallery'],
    '/tarife': ['bookings'],
    '/rates': ['bookings'],
    '/rezervari': ['bookings'],
    '/reservations': ['bookings'],
    '/politica-confidentialitate': ['privacyPolicy'],
    '/privacy': ['privacyPolicy'],
    '/termeni': ['cookieConsent'],
    '/terms': ['cookieConsent'],
  },
  ns: [
    'common',
    'nav',
    'footer',
    'hero',
    'home',
    'usp',
    'cabin',
    'testimonials',
    'gallery',
    'contact',
    'bookings',
    'faq',
    'privacyPolicy',
    'cookieConsent',
  ],
  defaultNS: 'common',
};
